#!/usr/bin/env ansible-playbook

- hosts: localhost
  connection: local
  become: yes

  vars:
    compose_home: /var/server/config

  tasks:
  - include: playbooks/docker-base.yml tags=docker
  - include: playbooks/jenkins.yml tags=jenkins
    vars:
      settings:
        - playbooks/vars/jenkins.yml

